In [1]:
#machine learning is divided into three types:
#i)supervised(it is like school basic learning where we are provided the info and then we learn)
#ii)unsupervised(here patterns are formed from the given data and then divided into grps for further programming)
#iii)reinforcement(environment,agent,reward,penanlty,goal-it is like a cycle where the user has to work in an environment to reach the goal where there are multiple obstacles which leads to penalty and rewards acc to given condition))

#supervised machine learning is of two types:
#i)regression - numerical data
#ii)classification - categorical data gives binary output

In [2]:
#MACHINE LEARNING GUIDE
#step1- import all libraries

In [3]:
#step2- import dataset using pandas (pd.read_csv, pd.read_excel)

In [4]:
#step3- eda or cleaning or preprocessing our dataset

In [5]:
#step4- target variables select(x,y(x is input data and y is output data))

In [6]:
#step5- data divide into two parts (training and testing (x,y both)) train_test_split()

In [7]:
#step6- import model (lr=linear regression)

In [8]:
#step7- training data will be fitt on model (lr.fit(x_train,y_train)

In [9]:
#step8- make predictions  (lr.predict(x_test))

In [10]:
#step9- check model evaluation matrices (r2 score, mse, mae, fiscore, precision, recall,accuracy score)

In [11]:
#step10- convert model into pkl file and then we will make gui and make predictions using frontend

In [54]:
import pickle

In [12]:
import numpy as np
import pandas as pd

df=pd.read_csv("sales_data.csv")
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [13]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [14]:
df.shape

(1000, 14)

In [15]:
x=df[["Quantity_Sold"]]
y=df["Unit_Price"]

In [46]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(x, y , test_size = 0.2 , random_state = 42)
from sklearn.linear_model import LinearRegression

In [17]:
lr=LinearRegression()
lr.fit(X_train , y_train)

LinearRegression()

In [18]:
y_pred=lr.predict(X_test)
y_pred

array([2720.95429168, 2735.42418324, 2605.19515914, 2740.24748043,
       2585.90197039, 2590.72526757, 2716.13099449, 2725.77758887,
       2706.48440011, 2629.31164509, 2658.25142822, 2774.01056076,
       2634.13494228, 2706.48440011, 2658.25142822, 2706.48440011,
       2605.19515914, 2802.95034389, 2778.83385795, 2614.84175352,
       2745.07077762, 2764.36396638, 2798.1270467 , 2672.72131979,
       2764.36396638, 2730.60088606, 2749.89407481, 2735.42418324,
       2638.95823946, 2783.65715513, 2619.66505071, 2696.83780573,
       2634.13494228, 2663.07472541, 2788.48045232, 2692.01450854,
       2745.07077762, 2614.84175352, 2802.95034389, 2682.36791417,
       2759.54066919, 2663.07472541, 2749.89407481, 2600.37186195,
       2614.84175352, 2730.60088606, 2807.77364108, 2663.07472541,
       2798.1270467 , 2624.4883479 , 2677.54461698, 2745.07077762,
       2663.07472541, 2745.07077762, 2730.60088606, 2793.30374951,
       2638.95823946, 2643.78153665, 2793.30374951, 2590.72526757,
       2648.60483384, 2663.07472541, 2667.8980226 , 2798.1270467 ,
       2658.25142822, 2585.90197039, 2778.83385795, 2672.72131979,
       2749.89407481, 2605.19515914, 2667.8980226 , 2807.77364108,
       2749.89407481, 2600.37186195, 2610.01845633, 2706.48440011,
       2677.54461698, 2740.24748043, 2730.60088606, 2663.07472541,
       2638.95823946, 2798.1270467 , 2643.78153665, 2619.66505071,
       2663.07472541, 2692.01450854, 2769.18726357, 2696.83780573,
       2692.01450854, 2648.60483384, 2735.42418324, 2749.89407481,
       2595.54856476, 2725.77758887, 2624.4883479 , 2701.66110292,
       2745.07077762, 2600.37186195, 2687.19121135, 2812.59693827,
       2745.07077762, 2624.4883479 , 2663.07472541, 2807.77364108,
       2706.48440011, 2783.65715513, 2687.19121135, 2629.31164509,
       2701.66110292, 2716.13099449, 2643.78153665, 2610.01845633,
       2711.3076973 , 2585.90197039, 2764.36396638, 2605.19515914,
       2817.42023546, 2624.4883479 , 2677.54461698, 2600.37186195,
       2807.77364108, 2817.42023546, 2667.8980226 , 2643.78153665,
       2638.95823946, 2672.72131979, 2730.60088606, 2783.65715513,
       2812.59693827, 2677.54461698, 2590.72526757, 2807.77364108,
       2648.60483384, 2600.37186195, 2783.65715513, 2740.24748043,
       2807.77364108, 2590.72526757, 2725.77758887, 2696.83780573,
       2711.3076973 , 2682.36791417, 2798.1270467 , 2687.19121135,
       2614.84175352, 2614.84175352, 2706.48440011, 2585.90197039,
       2677.54461698, 2585.90197039, 2595.54856476, 2600.37186195,
       2725.77758887, 2629.31164509, 2720.95429168, 2614.84175352,
       2672.72131979, 2730.60088606, 2774.01056076, 2764.36396638,
       2735.42418324, 2711.3076973 , 2658.25142822, 2590.72526757,
       2677.54461698, 2687.19121135, 2643.78153665, 2677.54461698,
       2812.59693827, 2677.54461698, 2749.89407481, 2807.77364108,
       2740.24748043, 2716.13099449, 2590.72526757, 2629.31164509,
       2658.25142822, 2706.48440011, 2692.01450854, 2701.66110292,
       2802.95034389, 2788.48045232, 2793.30374951, 2802.95034389,
       2643.78153665, 2672.72131979, 2619.66505071, 2667.8980226 ,
       2798.1270467 , 2638.95823946, 2807.77364108, 2749.89407481,
       2735.42418324, 2595.54856476, 2624.4883479 , 2610.01845633,
       2600.37186195, 2759.54066919, 2600.37186195, 2769.18726357])

In [19]:
X_test

     Quantity_Sold
521             29
737             32
740              5
660             33
411              1
..             ...
408              6
332              4
208             37
613              4
78              39

[200 rows x 1 columns]

In [20]:
y_test

521    3607.15
737    3711.47
740    2490.47
660    1994.01
411    1535.57
        ...
408    4061.37
332    3893.60
208    4172.35
613    4280.06
78     3931.25
Name: Unit_Price, Length: 200, dtype: float64

In [21]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test ,y_pred)
r2

-5.2327452143341446e-05

In [56]:
import pickle
with open("sales_prediction_model.pkl", "wb") as file:
    pickle.dump(lr, file)

print("Model saved successfully!")

Model saved successfully!

In [57]:
import joblib
joblib.dump(lr, "sales_prediction_model.pkl")

print("Model saved successfully!")

Model saved successfully!