In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv("breast_cancer.csv")
df

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...
678,3,1,1,1,3,2,1,1,1,2
679,2,1,1,1,2,1,1,1,1,2
680,5,10,10,3,7,3,8,10,2,4
681,4,8,6,4,3,4,10,6,1,4
682,4,8,8,5,4,5,10,4,1,4

In [3]:
print(df.head())

   Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1
1                5                        4                         4
2                3                        1                         1
3                6                        8                         8
4                4                        1                         1

   Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
0                  1                            2            1
1                  5                            7           10
2                  1                            2            2
3                  1                            3            4
4                  3                            2            1

   Bland Chromatin  Normal Nucleoli  Mitoses  Class
0                3                1        1      2
1                3                2        1      2
2                3                1        1      2
3                3                7        1      2
4                3                1        1      2

In [4]:
df.tail()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
678,3,1,1,1,3,2,1,1,1,2
679,2,1,1,1,2,1,1,1,1,2
680,5,10,10,3,7,3,8,10,2,4
681,4,8,6,4,3,4,10,6,1,4
682,4,8,8,5,4,5,10,4,1,4

In [5]:
df.isnull().sum()

Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [6]:
X = df.drop('Class',axis=1)
y = df['Class']

y = pd.get_dummies(y, columns=['Class'], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

classifier = LogisticRegression()
classifier.fit(X_train , y_train)

C:\Users\Sanya\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [7]:
y_pred = classifier.predict(X_test)
y_pred

array([ True,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False,  True,
       False,  True,  True, False,  True, False, False, False,  True,
        True, False, False, False,  True,  True,  True, False, False,
        True, False,  True,  True, False,  True,  True, False, False,
        True, False,  True, False,  True, False, False, False,  True,
       False,  True,  True, False, False,  True, False, False, False,
        True, False, False,  True,  True, False, False,  True, False,
       False, False,  True,  True, False, False,  True,  True,  True,
        True, False,  True, False,  True, False, False,  True, False,
       False,  True, False, False, False, False,  True,  True, False,
       False, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True,  True, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
        True, False,  True, False, False, False,  True,  True,  True,
       False, False])

In [8]:
y_test

         4
292   True
145   True
211  False
118  False
302  False
..     ...
110   True
82    True
51    True
210  False
548  False

[137 rows x 1 columns]

In [9]:
from sklearn.metrics import accuracy_score , classification_report

In [10]:
print(accuracy_score(y_pred,y_test))

0.9562043795620438

In [11]:
print(classification_report(y_pred , y_test))

              precision    recall  f1-score   support

       False       0.99      0.94      0.96        83
        True       0.91      0.98      0.95        54

    accuracy                           0.96       137
   macro avg       0.95      0.96      0.95       137
weighted avg       0.96      0.96      0.96       137

In [13]:
import pickle
pickle.dump(classifier, open("cancer.pkl", "wb"))
print("model saved")

model saved